cimod: cimod.model.binary_quadratic_model Namespace Reference
cimod.model.binary_quadratic_model Namespace Reference
Functions
get_cxxcimod_class (linear, quadratic, sparse)
extract_offset_and_vartype (*args, **kwargs)
make_BinaryQuadraticModel (linear, quadratic, sparse)
make_BinaryQuadraticModel_from_JSON (obj)
BinaryQuadraticModel (linear, quadratic, *args, **kwargs)
bqm_from_numpy_matrix (mat, list variables=None, offset=0.0, vartype="BINARY", **kwargs)
bqm_from_qubo (Q, offset=0.0, **kwargs)
bqm_from_ising (linear, quadratic, offset=0.0, **kwargs)
Variables
from_numpy_matrix
from_qubo
from_ising
from_serializable
model_type
Function Documentation
BinaryQuadraticModel()
cimod.model.binary_quadratic_model.BinaryQuadraticModel (linear, quadratic, * args, ** kwargs)
References declare_BQM(), and cimod.model.binary_quadratic_model.extract_offset_and_vartype().
bqm_from_ising()
cimod.model.binary_quadratic_model.bqm_from_ising (linear, quadratic, offset = 0.0, ** kwargs)
References declare_BQM(), and cimod.model.binary_quadratic_model.from_ising.
bqm_from_numpy_matrix()
cimod.model.binary_quadratic_model.bqm_from_numpy_matrix (mat, list variables = None, offset = 0.0, vartype = "BINARY", ** kwargs)
References declare_BQM(), and cimod.model.binary_quadratic_model.from_numpy_matrix.
bqm_from_qubo()
cimod.model.binary_quadratic_model.bqm_from_qubo (Q, offset = 0.0, ** kwargs)
References declare_BQM(), and cimod.model.binary_quadratic_model.from_qubo.
extract_offset_and_vartype()
cimod.model.binary_quadratic_model.extract_offset_and_vartype (* args, ** kwargs)
References declare_BQM().
Referenced by cimod.model.binary_quadratic_model.BinaryQuadraticModel().
get_cxxcimod_class()
cimod.model.binary_quadratic_model.get_cxxcimod_class (linear, quadratic, sparse)
References declare_BQM().
Referenced by cimod.model.binary_quadratic_model.make_BinaryQuadraticModel().
make_BinaryQuadraticModel()
cimod.model.binary_quadratic_model.make_BinaryQuadraticModel (linear, quadratic, sparse)
BinaryQuadraticModel factory.
   Generate BinaryQuadraticModel class with the base class specified by the arguments linear and quadratic
Args:
    linear (dict): linear bias
    quadratic (dict): quadratic bias
    sparse (bool): if true, the inner data will be a sparse matrix, otherwise the data will be a dense matrix
Returns:
    generated BinaryQuadraticModel class
References declare_BQM(), and cimod.model.binary_quadratic_model.get_cxxcimod_class().
make_BinaryQuadraticModel_from_JSON()
cimod.model.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON (obj)
References declare_BQM().
Variable Documentation
from_ising
cimod.model.binary_quadratic_model.from_ising
Referenced by cimod.model.binary_quadratic_model.bqm_from_ising().
from_numpy_matrix
cimod.model.binary_quadratic_model.from_numpy_matrix
Referenced by cimod.model.binary_quadratic_model.bqm_from_numpy_matrix().
from_qubo
cimod.model.binary_quadratic_model.from_qubo
Referenced by cimod.model.binary_quadratic_model.bqm_from_qubo().
from_serializable
cimod.model.binary_quadratic_model.from_serializable
model_type
cimod.model.binary_quadratic_model.model_type