cimod: cimod.model.binary_polynomial_model Namespace Reference
cimod.model.binary_polynomial_model Namespace Reference
Classes
class Polynomial
Functions
make_BinaryPolynomialModel (polynomial, index_type=None, tuple_size=0)
make_BinaryPolynomialModel_from_JSON (obj)
BinaryPolynomialModel (*args, **kwargs)
_BinaryPolynomialModel_from_dict (dict polynomial, vartype)
_BinaryPolynomialModel_from_list (list keys, list values, vartype)
make_BinaryPolynomialModel_from_hising (*args, **kwargs)
_make_BinaryPolynomialModel_from_hising_from_dict (dict polynomial)
_make_BinaryPolynomialModel_from_hising_from_list (list keys, list values)
make_BinaryPolynomialModel_from_hubo (*args, **kwargs)
_make_BinaryPolynomialModel_from_hubo_from_dict (dict polynomial)
_make_BinaryPolynomialModel_from_hubo_from_list (list keys, list values)
Variables
from_serializable
from_hising
from_hubo
index_type
model_type
vartype
Function Documentation
_BinaryPolynomialModel_from_dict()
cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_dict (dict polynomial, vartype) protected
References declare_BQM().
Referenced by cimod.model.binary_polynomial_model.BinaryPolynomialModel().
_BinaryPolynomialModel_from_list()
cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_list (list keys, list values, vartype) protected
References declare_BQM().
Referenced by cimod.model.binary_polynomial_model.BinaryPolynomialModel().
_make_BinaryPolynomialModel_from_hising_from_dict()
cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_dict (dict polynomial) protected
References cimod.model.binary_polynomial_model.from_hising.
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hising().
_make_BinaryPolynomialModel_from_hising_from_list()
cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_list (list keys, list values) protected
References declare_BQM(), and cimod.model.binary_polynomial_model.from_hising.
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hising().
_make_BinaryPolynomialModel_from_hubo_from_dict()
cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_dict (dict polynomial) protected
References cimod.model.binary_polynomial_model.from_hubo.
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hubo().
_make_BinaryPolynomialModel_from_hubo_from_list()
cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list (list keys, list values) protected
References declare_BQM(), and cimod.model.binary_polynomial_model.from_hubo.
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hubo().
BinaryPolynomialModel()
cimod.model.binary_polynomial_model.BinaryPolynomialModel (* args, ** kwargs)
References cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_dict(), cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_list(), and declare_BQM().
make_BinaryPolynomialModel()
cimod.model.binary_polynomial_model.make_BinaryPolynomialModel (polynomial, index_type = None, tuple_size = 0)
BinaryPolynomialModel factory.
   Generate BinaryPolynomialModel class with the base class specified by the arguments linear and quadratic
Args:
    polynomial (dict): polynomial bias including linear bias
Returns:
    generated BinaryPolynomialModel class
References declare_BQM().
make_BinaryPolynomialModel_from_hising()
cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hising (* args, ** kwargs)
References cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_dict(), cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_list(), and declare_BQM().
make_BinaryPolynomialModel_from_hubo()
cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hubo (* args, ** kwargs)
References cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_dict(), cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list(), and declare_BQM().
make_BinaryPolynomialModel_from_JSON()
cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_JSON (obj)
References declare_BQM().
Variable Documentation
from_hising
cimod.model.binary_polynomial_model.from_hising
Referenced by cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_dict(), and cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_list().
from_hubo
cimod.model.binary_polynomial_model.from_hubo
Referenced by cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_dict(), and cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list().
from_serializable
cimod.model.binary_polynomial_model.from_serializable
index_type
cimod.model.binary_polynomial_model.index_type
model_type
cimod.model.binary_polynomial_model.model_type
vartype
cimod.model.binary_polynomial_model.vartype