cimod: cimod.model.legacy.binary_quadratic_model Namespace Reference
cimod.model.legacy.binary_quadratic_model Namespace Reference
Functions
make_BinaryQuadraticModel (linear, quadratic)
make_BinaryQuadraticModel_from_JSON (obj)
BinaryQuadraticModel (linear, quadratic, *args, **kwargs)
Variables
from_qubo
Q
offset
from_ising
linear
quadratic
from_serializable
_re_calculate
_re_calculate_indices
_interaction_matrix
_indices
_ind_to_num
vartype
Function Documentation
BinaryQuadraticModel()
cimod.model.legacy.binary_quadratic_model.BinaryQuadraticModel (linear, quadratic, * args, ** kwargs)
References declare_BQM().
make_BinaryQuadraticModel()
cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel (linear, quadratic)
BinaryQuadraticModel factory.
   Generate BinaryQuadraticModel class with the base class specified by the arguments linear and quadratic
Args:
    linear (dict): linear bias
    quadratic (dict): quadratic bias
Returns:
    generated BinaryQuadraticModel class
References declare_BQM().
make_BinaryQuadraticModel_from_JSON()
cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON (obj)
References declare_BQM().
Variable Documentation
_ind_to_num
cimod.model.legacy.binary_quadratic_model._ind_to_num protected
_indices
cimod.model.legacy.binary_quadratic_model._indices protected
_interaction_matrix
cimod.model.legacy.binary_quadratic_model._interaction_matrix protected
_re_calculate
cimod.model.legacy.binary_quadratic_model._re_calculate protected
_re_calculate_indices
cimod.model.legacy.binary_quadratic_model._re_calculate_indices protected
from_ising
cimod.model.legacy.binary_quadratic_model.from_ising
from_qubo
cimod.model.legacy.binary_quadratic_model.from_qubo
from_serializable
cimod.model.legacy.binary_quadratic_model.from_serializable
linear
cimod.model.legacy.binary_quadratic_model.linear
offset
cimod.model.legacy.binary_quadratic_model.offset
Q
cimod.model.legacy.binary_quadratic_model.Q
quadratic
cimod.model.legacy.binary_quadratic_model.quadratic
vartype
cimod.model.legacy.binary_quadratic_model.vartype